### ISSUE TITLE
 Error: Cannot find module 'ws'

### ISSUE THREAD

**Issue by empierre** [chpmrc/foscam_streamer#1]
Hello,

  can't launch it, module error ?

:~/foscam_streamer$ node index.js 
module.js:327
    throw err;
    ^

Error: Cannot find module 'ws'

**Comment by elchiapp** [comment]
Hi empierre, please run `npm install` before you run the server. It's a standard for any Node project.

**Comment by empierre** [comment]
I did it, even a -g and it didn't work

**Comment by elchiapp** [comment]
That's weird, I just cloned the repository, `npm install` and `node index.js` and everything works. Could you please sheare your node and npm versions?

**Comment by empierre** [comment]
trying on another machine,

rror: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:870:11)

I guess you should add also to install ffmpeg ;-)

**Comment by empierre** [comment]
Hello,

  went a bit further but:

  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
  undefined: No such file or directory

  and opening the test page I see nothing

**Comment by empierre** [comment]
back on my PI B:
$ npm install 
npm info using npm@2.14.7
npm info using node@v4.2.2
npm WARN package.json rtsp@1.0.0 No repository field.
npm info preinstall rtsp@1.0.0
npm info build /home/pi/foscam_streamer
npm info linkStuff rtsp@1.0.0
npm info install rtsp@1.0.0
npm info postinstall rtsp@1.0.0
npm info prepublish rtsp@1.0.0

$ node index.js
npm info ok 
    throw err;
    ^

Error: Cannot find module 'ws'

**Comment by roysG** [comment]
I also get it, any updates?
