### ISSUE TITLE
Doesn't stream correctly

### ISSUE THREAD

**Issue by hupptechnologies** [chpmrc/foscam_streamer#5]
Please see below screenshot how it render.
I played the rtsp in vlc palyer and it's perfect, but when played through this library, it appeared as in screenshot.

![screenshot from 2018-02-02 12-48-40](https://user-images.githubusercontent.com/30364569/35721520-77521b66-0818-11e8-8310-c40fa39cf775.png)

Below logs on node terminal : 

Past duration 0.799995 too large  362908kB time=00:21:04.50 bitrate=2351.1kbits/s dup=12639 drop=5 speed=   1x
Last message repeated 4 times

**Comment by greenygh0st** [comment]
Same issue here

**Comment by chpmrc** [comment]
Have you checked that the streaming resolution is the same as the script?

**Comment by hupptechnologies** [comment]
Yes checked that already.

**Comment by patelShreyaP** [comment]
I have same problem.
In 1280 x 720 it is working fine.
![1280_720px](https://user-images.githubusercontent.com/40856658/42318090-a45da118-806b-11e8-83fa-ded4d904dfe6.png)

but in other resolution eg(720 x 480)
it shows 
![otherresolution](https://user-images.githubusercontent.com/40856658/42318288-2732c46a-806c-11e8-8d1e-03103728d3fc.png)


i did this changes in mpeg1muxer.js file 
var args = ('-i ' + this.url + ' -vf scale=720:480 -f mpeg1video -b:v 1000k -an -r 24 -').split(' ')

**Comment by ducati1224** [comment]
@patelShreyaP you should try:
var args = ("-rtsp_transport tcp -i " + this.url + " -s 720x480 -f mpeg1video -b:v 1000k -an -r 24 -").split(" ");

**Comment by aluminiumgeek** [comment]
**The solution** is to change width/height in `index.html` to the actual size of your video.

**Comment by hupptechnologies** [comment]
I am closing as I am not working on this solution anymore.
